#!/usr/bin/php
<?php
/* This script takes in a json generated by parselogs.php and
 * builds reports for execution time organized by task and by node provider.
 */
$dir = new DirectoryIterator(dirname(__FILE__).'/dump/');
$profile = array();
$profiles=0;

pcntl_signal(SIGHUP,  function($signo) {
  global $profile;
  echo json_encode($profile)."\n";
});
pcntl_signal(SIGTERM,  function($signo) {
  print_exit();
});
pcntl_signal(SIGINT,  function($signo) {
  print_exit();
});

foreach ($dir as $f) {
  if (!$f->isFile()) continue;
  $c = file_get_contents('dump/'.$f);
  if (!preg_match('/Building remotely on <a .*>([^<]+)-[0-9]+<\/a>/', $c, $m)) {
    echo "Failed to find node type of $f\n";
    continue;
  }
  $nodetype = $m[1];
  foreach (explode("\n", $c) as $l) {
    if (preg_match('/(?:[^|]+)\|\s+(.*)\s+[-]+\s+([0-9\.s]+)s\s*$/', $l, $m)) {
      $role_task = $m[1];
      $seconds = (float)$m[2];
      $profile[$role_task][$nodetype][] = $seconds;
    }
  }
  $profiles++;
  pcntl_signal_dispatch();
}

print_exit();

function print_exit() {
  global $profile, $profiles;
  file_put_contents("php://stderr", "\nExiting with $profiles profiles completed.\n");
  exit(json_encode($profile));
}

?>
